### ISSUE TITLE
List user rules is empty

### ISSUE THREAD

**Issue by FireworkerWeb** [DNN-Connect/UserAccountRegistration#16]
I installed UserAccountRegistration module rel. 1.3.0 on DNN 7.4.0 (italian site).
When I edit a user and go to rules tab, the rules combo is empty and does not allow me to add a new rule.
I await a reply, thanks.
Regards

**Comment by peppertree** [comment]
I assume you are talking about the useraccount management module, right? I guess you have not set the allowed roles setting to include any roles. The roles dropdown will only let you set roles you area allowed to set.

For more questions please go to the correct issue tracker:
https://github.com/DNN-Connect/UserAccountManagement/issues

Closing this here.

**Comment by FireworkerWeb** [comment]
Yes, sorry, I talk about the UserAccount Management module.
The permissions are set correctly (I'm doing tests with the Host user who has all rights); if I use the standard form DNN (User Roles) I can set, but if I use UserAccount Management, the combo remains empty.
I solved the problem by inserting the module in a new page, without other modules, and now the combo is populated!
Thanks
Regards
